"""Backfill historical chat threads.

For any resolved/closed session that has no messages, we reconstruct the
iMessage thread. The outbound messages (Ditto's debrief prompt to each user
and the outcome-specific confirmation) are the exact same templates the live
flow uses in `services.session_service.create_session` and the graph nodes,
so scripted/live scenarios and backfilled history read identically on the
Sessions detail view.

Only the *inbound* replies are generated by Claude. Sonnet-4-5 writes each
user's reply from their known persona, choice, interest level, memorable
moments, and concerns. Each call writes one `agent_traces` row so backfill
activity is visible alongside other agent traffic.
"""

from __future__ import annotations

import asyncio
from datetime import timedelta

from pydantic import Field

from afters.db.mongo import collections, get_db
from afters.llm.client import get_llm
from afters.models import AftersSession, Base, Message, User


# Canonical outbound templates. These must stay in sync with:
#   services/session_service.py::create_session         (debrief prompt)
#   graph/machine.py::node_both_again_confirm           (both_again)
#   graph/machine.py::node_both_group_confirm           (both_group)
#   graph/machine.py::node_both_pass_noop               (both_pass)
#   graph/machine.py::node_timeout_handler              (timed_out)
#
# If you change the wording in either place, update the other.

DEBRIEF_PROMPT = (
    "hey {first}. quick check in from afters. "
    "how did it go? you can reply three ways: "
    "again (want another date), group (chill group hang), or "
    "pass (no second date). or just talk to me in your own words "
    "and i'll read between the lines."
)

BOTH_AGAIN_CONFIRM = (
    "good news {first}. they also said yes to a second one. "
    "we'll line up a spot and a time and send it through in the next message."
)

BOTH_GROUP_CONFIRM = (
    "nice one {first}. we put you both in the group queue. "
    "you'll hear from us within a week once we line up 4 to 6 people "
    "with a similar vibe."
)

BOTH_PASS_CONFIRM = (
    "thanks for letting us know {first}. "
    "we'll find you someone better suited next wednesday."
)

TIMED_OUT_SOFT_CLOSE = (
    "hey {first}. the other person didn't get back to us this week. "
    "we called it here so you aren't left hanging. next wednesday we'll "
    "line up someone who follows up faster."
)


class BackfilledReplies(Base):
    user_a_reply: str = Field(
        max_length=280,
        description=(
            "User A's inbound reply to Ditto's debrief prompt. First-person, "
            "lowercase, Gen Z casual, apostrophes in contractions. Under 280 "
            "chars. Shaped by their choice, interest level, memorable moments, "
            "and concerns. Feels like a real text, not a review."
        ),
    )
    user_b_reply: str = Field(
        max_length=280,
        description=(
            "User B's inbound reply. Same voice rules. If user B is marked "
            "pending (did not respond), return an empty string."
        ),
    )


SYSTEM = """You are the Afters post-date chat historian. For each user in a Ditto post-date session, write the inbound text they'd send back to Ditto's standard debrief prompt.

Voice rules (strict):
- lowercase only. keep apostrophes in contractions (don't, you'll, i'd, we'll, that's, they're, aren't).
- Gen Z casual. short sentences. no em dashes. no exclamation points.
- each reply under 220 chars. should feel like a real text, not a review or an essay.
- use the user's memorable_moments as anchors when natural; reference concerns if they have any.
- do NOT invert the choice. if they picked 'group', they liked the person and want a group hang (not rejection). if they picked 'pass', they opted out but are kind about it. if they picked 'again', they want another one-on-one.
- do NOT invent facts not in their moments/concerns. stay grounded in what's given.

You write only the inbound replies. The outbound prompts and any outcome-specific confirmation messages are NOT your job; those are handled by the platform templates.
"""


async def _load_user(user_id: str) -> User:
    raw = await get_db()[collections.users].find_one({"_id": user_id})
    return User.model_validate(raw)


def _first(name: str) -> str:
    return name.split()[0].lower()


async def backfill_messages_for_session(
    session: AftersSession,
    *,
    force: bool = False,
) -> int:
    """Generate and insert the full iMessage thread for one session.

    No-op if the session already has messages and `force` is False. Returns
    the number of messages written.
    """
    db = get_db()
    existing = await db[collections.messages].count_documents(
        {"session_id": session.id}
    )
    if existing > 0 and not force:
        return 0
    if existing > 0 and force:
        await db[collections.messages].delete_many({"session_id": session.id})

    user_a = await _load_user(session.participants[0].user_id)
    user_b = await _load_user(session.participants[1].user_id)
    p_a = session.participants[0]
    p_b = session.participants[1]

    a_responded = p_a.response_state != "pending"
    b_responded = p_b.response_state != "pending"

    # Venue context is only for Claude to ground the replies, not for the
    # outbound copy. The outbound uses the canonical template.
    date_raw = await db[collections.dates].find_one({"_id": session.date_id})
    venue_name = "the first-date venue"
    if date_raw:
        venue_raw = await db[collections.venues].find_one({"_id": date_raw["venue_id"]})
        if venue_raw:
            venue_name = venue_raw["name"]

    user_msg = (
        f"Campus: {session.campus}\n"
        f"First-date venue: {venue_name}\n"
        f"Outcome: {session.resolved_outcome}\n\n"
        f"User A: {user_a.name} ({user_a.year} {user_a.pronouns})\n"
        f"  persona: {user_a.profile.persona_summary}\n"
        f"  choice: {p_a.choice or 'pending'}\n"
        f"  interest_level: {p_a.interest_level if p_a.interest_level is not None else 'n/a'}/10\n"
        f"  memorable_moments: {p_a.memorable_moments or 'none recorded'}\n"
        f"  concerns: {p_a.concerns or 'none'}\n"
        f"  response_state: {p_a.response_state}\n\n"
        f"User B: {user_b.name} ({user_b.year} {user_b.pronouns})\n"
        f"  persona: {user_b.profile.persona_summary}\n"
        f"  choice: {p_b.choice or 'pending'}\n"
        f"  interest_level: {p_b.interest_level if p_b.interest_level is not None else 'n/a'}/10\n"
        f"  memorable_moments: {p_b.memorable_moments or 'none recorded'}\n"
        f"  concerns: {p_b.concerns or 'none'}\n"
        f"  response_state: {p_b.response_state}\n\n"
        "Write each user's inbound reply. If a user's response_state is "
        "'pending', return an empty string for that reply (they never wrote back)."
    )

    def summary(parsed: BackfilledReplies, latency_ms: int) -> str:
        n = int(bool(parsed.user_a_reply.strip())) + int(bool(parsed.user_b_reply.strip()))
        return (
            f"Backfill Agent wrote {n} inbound reply(ies) for session "
            f"{session.id[-6:]} ({session.resolved_outcome}) "
            f"in {latency_ms}ms using sonnet."
        )

    replies = await get_llm().structured(
        agent_name="Backfill Agent",
        session_id=session.id,
        model="claude-sonnet-4-5",
        system=SYSTEM,
        user=user_msg,
        schema_cls=BackfilledReplies,
        tool_name="emit_replies",
        tool_description="Emit both users' inbound text replies.",
        summary_builder=summary,
        input_summary=(
            f"{user_a.name} + {user_b.name} @ {session.campus}; "
            f"outcome={session.resolved_outcome}"
        ),
        temperature=0.7,
        tags=["backfill_agent", "sonnet", session.resolved_outcome or "unresolved"],
    )

    first_a = _first(user_a.name)
    first_b = _first(user_b.name)
    start = session.created_at
    resolved_at = session.resolved_at or (start + timedelta(hours=3))

    msgs: list[Message] = []

    # 1. Canonical outbound debrief prompt to each user.
    msgs.append(
        Message(
            user_id=user_a.id,
            direction="outbound",
            body=DEBRIEF_PROMPT.format(first=first_a),
            kind="text",
            session_id=session.id,
            created_at=start,
        )
    )
    msgs.append(
        Message(
            user_id=user_b.id,
            direction="outbound",
            body=DEBRIEF_PROMPT.format(first=first_b),
            kind="text",
            session_id=session.id,
            created_at=start + timedelta(seconds=2),
        )
    )

    # 2. Claude-generated inbound replies, but only for participants who
    #    actually responded. Pending participants (e.g. the ghost in a
    #    timed_out session) keep their thread at just the outbound prompt.
    if a_responded and replies.user_a_reply.strip():
        msgs.append(
            Message(
                user_id=user_a.id,
                direction="inbound",
                body=replies.user_a_reply.strip(),
                kind="text",
                session_id=session.id,
                created_at=p_a.submitted_at or (start + timedelta(hours=1)),
            )
        )
    if b_responded and replies.user_b_reply.strip():
        msgs.append(
            Message(
                user_id=user_b.id,
                direction="inbound",
                body=replies.user_b_reply.strip(),
                kind="text",
                session_id=session.id,
                created_at=p_b.submitted_at or (start + timedelta(hours=2)),
            )
        )

    # 3. Outcome-specific outbound confirmation. Exact copy matches the live
    #    graph nodes. Asymmetric outcomes get no confirmation because closure
    #    is pending human review in that branch.
    outcome = session.resolved_outcome
    if outcome == "both_again":
        for user, first in ((user_a, first_a), (user_b, first_b)):
            msgs.append(
                Message(
                    user_id=user.id,
                    direction="outbound",
                    body=BOTH_AGAIN_CONFIRM.format(first=first),
                    kind="text",
                    session_id=session.id,
                    created_at=resolved_at,
                )
            )
    elif outcome == "both_group":
        for user, first in ((user_a, first_a), (user_b, first_b)):
            msgs.append(
                Message(
                    user_id=user.id,
                    direction="outbound",
                    body=BOTH_GROUP_CONFIRM.format(first=first),
                    kind="text",
                    session_id=session.id,
                    created_at=resolved_at,
                )
            )
    elif outcome == "both_pass":
        for user, first in ((user_a, first_a), (user_b, first_b)):
            msgs.append(
                Message(
                    user_id=user.id,
                    direction="outbound",
                    body=BOTH_PASS_CONFIRM.format(first=first),
                    kind="text",
                    session_id=session.id,
                    created_at=resolved_at,
                )
            )
    elif outcome == "timed_out":
        # Soft close only goes to whichever user actually replied.
        if a_responded:
            msgs.append(
                Message(
                    user_id=user_a.id,
                    direction="outbound",
                    body=TIMED_OUT_SOFT_CLOSE.format(first=first_a),
                    kind="text",
                    session_id=session.id,
                    created_at=resolved_at,
                )
            )
        if b_responded:
            msgs.append(
                Message(
                    user_id=user_b.id,
                    direction="outbound",
                    body=TIMED_OUT_SOFT_CLOSE.format(first=first_b),
                    kind="text",
                    session_id=session.id,
                    created_at=resolved_at,
                )
            )
    # asymmetric_*: intentional no-op. Closure is pending human review.

    msgs.sort(key=lambda m: m.created_at)

    if msgs:
        await db[collections.messages].insert_many(
            [m.model_dump(by_alias=True) for m in msgs]
        )

    # Stash Claude's replies on the participants so the structured-debrief
    # "raw reply" panel stops showing the old '[historical, synthesized]'
    # placeholder.
    set_fields: dict = {}
    if a_responded and replies.user_a_reply.strip():
        set_fields["participants.0.raw_reply_text"] = replies.user_a_reply.strip()
    if b_responded and replies.user_b_reply.strip():
        set_fields["participants.1.raw_reply_text"] = replies.user_b_reply.strip()
    if set_fields:
        await db[collections.sessions].update_one(
            {"_id": session.id}, {"$set": set_fields}
        )

    return len(msgs)


async def backfill_all_missing(concurrency: int = 5, force: bool = False) -> dict:
    """Find every resolved or closed session with no messages and backfill
    concurrently. Returns a summary dict for the admin caller."""
    db = get_db()
    targets: list[AftersSession] = []
    async for raw in db[collections.sessions].find(
        {"state": {"$in": ["resolved", "closed"]}}
    ):
        session = AftersSession.model_validate(raw)
        if force:
            targets.append(session)
        else:
            count = await db[collections.messages].count_documents(
                {"session_id": session.id}
            )
            if count == 0:
                targets.append(session)

    sem = asyncio.Semaphore(concurrency)

    async def _one(s: AftersSession) -> int:
        async with sem:
            try:
                return await backfill_messages_for_session(s, force=force)
            except Exception as exc:  # noqa: BLE001
                print(f"[backfill] session {s.id} failed: {exc}")
                return 0

    counts = await asyncio.gather(*[_one(s) for s in targets])
    return {
        "sessions_inspected": len(targets),
        "sessions_backfilled": sum(1 for c in counts if c > 0),
        "messages_written": sum(counts),
        "force": force,
    }
