// Regenerates TypeScript types from afters-shared/schemas/*.json into src/_generated.ts.
// Not wired to the dashboard by default: src/types.ts is hand-written for DX,
// and this script exists so you can diff against the auto-generated version
// and know the hand-written shapes stayed in sync with the JSON Schemas.
// Run: pnpm --filter afters-shared codegen

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMAS_DIR = join(__dirname, "..", "schemas");
const OUT_FILE = join(__dirname, "..", "src", "_generated.ts");

async function main() {
  const files = (await readdir(SCHEMAS_DIR)).filter((f) => f.endsWith(".schema.json"));
  const parts: string[] = [
    "// GENERATED by afters-shared/scripts/codegen-ts.ts. Do not edit by hand.",
    "// Hand-written, ergonomic equivalents live in src/types.ts.",
    "",
  ];
  for (const f of files.sort()) {
    const raw = await readFile(join(SCHEMAS_DIR, f), "utf8");
    const schema = JSON.parse(raw);
    const code = await compile(schema, schema.title ?? f, {
      bannerComment: "",
      additionalProperties: false,
      style: { singleQuote: false },
    });
    parts.push(code.trim());
    parts.push("");
  }
  await writeFile(OUT_FILE, parts.join("\n"), "utf8");
  console.log(`wrote ${files.length} schemas to ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
